#!/usr/bin/env sh
# Generated by Gradle Wrapper
# This script forwards all arguments to the Gradle Wrapper JAR.
# It assumes the wrapper JAR is located at gradle/wrapper/gradle-wrapper.jar
# and that a valid gradle-wrapper.properties file exists.

# Resolve the directory containing this script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# If the wrapper JAR does not exist, download it using the wrapper properties
if [ ! -f "$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar" ]; then
  echo "Gradle wrapper JAR not found, downloading..."
  # Use the Gradle wrapper to download the correct version
  java -jar "$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar" --no-daemon --gradle-version 8.6
fi

# Execute the wrapper JAR with all passed arguments
exec java -jar "$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
