#!/usr/bin/env sh
# Gradle wrapper script generated by Gradle
# This script forwards all arguments to the Gradle Wrapper JAR.
# It assumes the wrapper JAR is located at gradle/wrapper/gradle-wrapper.jar
# and that a valid gradle-wrapper.properties file exists.

# Resolve the directory containing this script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Define the Java command (use the JDK installed by actions/setup-java)
JAVA_CMD="java"

# Execute the wrapper JAR
exec "$JAVA_CMD" -jar "$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
