#!/usr/bin/env sh
# ------------------------------------------------------------
# Gradle Wrapper startup script for POSIX platforms
# ------------------------------------------------------------
# This file was generated by the Gradle Wrapper tool.
# It is used to launch the Gradle build using a specific Gradle version.
# ------------------------------------------------------------
DEFAULT_JVM_OPTS=""
APP_NAME="gradlew"

# Resolve the location of the script and the project root
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG="$(dirname "$PRG")/$link"
  fi
done

# Get the directory containing this script
PRGDIR=`dirname "$PRG"`
# Resolve to absolute path
PRGDIR=`cd "$PRGDIR" && pwd`

# Determine the location of the wrapper JAR
WRAPPER_JAR="${PRGDIR}/gradle/wrapper/gradle-wrapper.jar"

# If the wrapper JAR does not exist, download it via the wrapper script itself
if [ ! -f "$WRAPPER_JAR" ]; then
  echo "Gradle wrapper JAR not found. Attempting to download..."
  # Use the tiny bootstrap that comes with the wrapper script (this will download the JAR automatically)
  # The following command will re-invoke the wrapper with the --no-daemon flag to force download.
  java -classpath "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain --no-daemon > /dev/null 2>&1 || true
fi

# Build the command line arguments
exec "$PRGDIR/gradle" "$@"
